### ISSUE TITLE
Buildings Should Show as Unburned Until/Unless Burned

### ISSUE THREAD

**Issue by mflaxman10** [RandomFractals/paradise-campfire-map#3]
Related to #2 

Current behavior:

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/2546667/54324274-5099c880-45ba-11e9-9584-4dc1556aa2e3.png">

Timeline has no apparent visual effect on structures burned - all that eventually burn are shown at time 0 as burnt already.

Expected behavior:

All buildings start as unburned ("Not exposed, not damaged")
The building damage counter shows 0 at time 0, and 9,042 at next time step (see table below)
After fire front hits them (i.e. playback date > perDatTime), they show their final fate based on the "Damage" field

Still hoping to update early fire times data if we can, but as of v3, here's what the relevant data look like:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/2546667/54324169-d79a7100-45b9-11e9-95d5-4fe99d7b7347.png">

**Comment by RandomFractals** [comment]
this is not true. Please try again and see all the endDateString sql query params in vega-spec.js for the map: https://github.com/RandomFractals/paradise-campfire-map/blob/master/src/common/vega-spec.js

All data displayed is according to your data records which also clearly shows that most structures burned in the first 2 days and for the remaining time span it was minor incremental if you replay it on the map at different zoom levels.
