### ISSUE TITLE
Colors for Damage Visualization

### ISSUE THREAD

**Issue by mflaxman10** [RandomFractals/paradise-campfire-map#5]
Current behavior:

Immerse default colors - no perceivable logic.

Expected behavior:

Continuous data (i.e. not categorical) should always be represented with a gradient.  We can pick any starting, middle and end colors we want.  But to be cartographically correct, they must be along a some visual axis.  

In this case, we plan to have fire intensity mapped along a yellow to red gradient.  So building damage should be along some spectrum which doesn't compete/overlap.  

As a start, I'd propose that unexposed buildings be represented as brown, and increasing levels of damage be monotonic grays to black.  Surviving structures are very special, and so need a bright highlight color - perhaps purple or pink - to stand out.

But it is crazy to try to specify verbally - we have a configuration and should have someone good at cartography pick final mix for presentation and review.  Also, if we happen to have someone color blind available, would be good to double check separability of final result with them.

In general, we are trying to plot 100k points on a small screen, so careful color choice will be critical to legibility.  We most want to emphasize the 500 points where exposed structured survived, so this is the cartographic goal.

**Comment by RandomFractals** [comment]
Current damage colors display in the bar chart and on the map at set to damage-color-palette.js we've discussed and agreed upon for configuring that color palette. 

Please see this related and possibly duplicate issue followup for more info: 

https://github.com/RandomFractals/paradise-campfire-map/issues/2#issuecomment-473057621
