### ISSUE TITLE
Apply Cartographic Exaggeration or Cross-filtering to Surviving Structures

### ISSUE THREAD

**Issue by mflaxman10** [RandomFractals/paradise-campfire-map#6]
Current behavior:

Unknown because we are rendering points

Expected behavior:

Need to make sure that 500 of 100k structures that survived render legibly without loosing performance.

Technique 1: render polygon 'strokes' with colors matching base fill color, but with thicker lines for surviving structures, and thinner ones for progressive degrees of damage.  Would presumably require back end Vega code change.  In GIS pre-testing, this shows promise, with line width of 2 pixels for surviving structures, down to 0.25 for destroyed ones.  Not sure how Vega rendering compares to GIS - lots of variation here in implementations.  Not possible in Immerse, so cannot easily test.

Technique 2: render in two passes, with surviving structures on top.  This would allow independent cartographic control of the critical points, but at some rendering time cost.  Not as visually sophisticated and adjustable as 1.  Not clear if performance rules this out.

Technique 3: enable cross-filter support on the bar chart similar to behavior in Immerse.  This would allow us to specifically focus on the surviving structures just by hiding the others.  Doesn't really solve the cartographic challenge for the first part of the demo, but allows phasing with a shift in attention.

**Comment by RandomFractals** [comment]
Latest map v. with buildings layer added colors them according to the damage color palette we agreed upon.
